version: '3.4'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data-example:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  web:
    image: example
    build:
      context: ./
      network: host
    environment:
      - DJANGO_SECRET_KEY=secret
    command: |
      bash -c "./wait-for postgres:5432 -- ./manage.py migrate &&  ./manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    depends_on:
      - postgres

  workers:
    image: example
    build:
      context: ./
      network: host
    environment:
      - DJANGO_SECRET_KEY=secret
    command: |
      bash -c "./wait-for postgres:5432 -- python ./manage.py runworkers"
    depends_on:
      - web

volumes:
  db-data-example: